
version: '3'
services:
  site:
    container_name: methuku
    command: jekyll serve --watch --drafts
    image: jekyll/jekyll:3.8.6
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000
