version: "2.1"
services:
  methuku:
    container_name: methuku
    command: jekyll serve
    image: jekyll/jekyll:3.8.6
    privileged: true
    volumes:
      - .:/srv/jekyll:Z
    ports:
      - 4000:4000
      - 35729:35729
    #   - 3000:3000
    # environment:
    #   - JEKYLL_ENV:production